-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users
CASCADE;
DROP TABLE IF EXISTS games_db
CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR (255) NOT NULL,
  password VARCHAR (255) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE games_db
(
  id SERIAL PRIMARY KEY NOT NULL,
  game_history JSON NOT NULL,
  player1 INTEGER REFERENCES users(id) ON DELETE CASCADE,
  player2 INTEGER REFERENCES users(id) ON DELETE CASCADE
);
